import { StyleSheet } from 'react-native';
import { moderateScale } from 'react-native-size-matters';

export default StyleSheet.create({
    container: {
        flex: moderateScale(1),
        backgroundColor:'#fff',
    },
    imageP:{
        height:moderateScale(130),
        width:moderateScale(130),
        borderRadius:moderateScale(100),
        overflow:'hidden',
        marginTop:moderateScale(20)
    },
    main:{
        paddingHorizontal:moderateScale(20),
        alignItems:'center',
        paddingBottom:moderateScale(60)
    },
    name:{
        fontSize:moderateScale(16),
        color:'#000',
        fontFamily:'Poppins-Medium',
        marginTop:moderateScale(10)
    },
    dflex:{
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'flex-start'
    },
    cMain:{
        width:'100%',
        marginTop:moderateScale(30)
    },
    pno:{
        fontSize:moderateScale(15),
        color:'#000',
        fontFamily:'Poppins-Medium'
    },
    nono:{
        fontSize:moderateScale(15),
        color:'#666',
        fontFamily:'Poppins-Regular'
    },
    icon:{
        marginRight:moderateScale(20)
    },
    mb30:{
        marginBottom:moderateScale(30)
    },
    editbtn:{
        alignItems:'center',
        justifyContent:'center',
        borderWidth:2.5,
        borderColor:'#B48618',
        borderRadius:moderateScale(50),
        paddingTop:moderateScale(12),
        paddingBottom:moderateScale(9),
    },
    idvider:{
        height:1,
        width:'80%',
        marginLeft:'10%',
        backgroundColor:'#666'
    },
    mt20:{
        marginTop:moderateScale(20)
    },
    logout:{
        color:'#FF0000'
    }
});